# fly.toml app configuration file generated for moeyy-mikuinvidious on 2023-10-16T16:48:20+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "moeyy-mikuinvidious"
primary_region = "hkg"
swap_size_mb = 512

[build]

[http_service]
  internal_port = 18888
  force_https = false
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
